num_iters: 30000
eval_every: 
save_every: 2000
device: auto
directory: illustrative
name: vanilla

env:
    name: illustrative
    max_nodes: 6
    max_degree:
    random_walk_length: 8
    add_degree: True
    add_clustering_coef: True
    add_shortest_path_length: True
model: 
    embed_dim: 256
    num_layers: 5
    num_heads: 4
trainer:
    train_size: 128
    sampling_size: 32
    sampling_freq: 1
    buffer_size: 2000
    exploration_epsilon: 0.1
    unif_backward: True
    correction_method: vanilla
    grad_norm_clip: 1.0
    lr: 0.0001
    min_lr:
    num_workers: 8