num_iters: 50000
eval_every: 
save_every: 500
device: auto
directory: synthetic
name: db-orbit

env:
    name: graph
    max_nodes: 7
    max_edges: 
    max_degree: 
    reward_name: "cliques"
    start_from_empty: True
    num_node_types: 2
    random_walk_length: 8
    add_degree: True
    add_clustering_coef: True
    add_shortest_path_length: True
model: 
    embed_dim: 256
    num_layers: 5
    num_heads: 4
trainer:
    training_method: 'db'
    sampling_tau: 0.95
    train_size: 512
    sampling_size: 16
    sampling_freq: 1
    buffer_size: 8000
    exploration_epsilon: 0.1
    unif_backward: True
    correction_method: vanilla
    grad_norm_clip: 1.0
    lr: 0.0001
    num_workers: 16
